####  Importing statements

In [1]:
import pandas as pd
import numpy as np
import requests
import scipy

import pyodbc

####  Get the url,the url is in JSON format

In [2]:
import requests

from flatten_json import flatten

resp = requests.get('https://api.punkapi.com/v2/beers')
txt = resp.json()
df = pd.DataFrame(txt)

####  Checking the content of the response

In [3]:
resp.content[:1000]

b'[{"id":1,"name":"Buzz","tagline":"A Real Bitter Experience.","first_brewed":"09/2007","description":"A light, crisp and bitter IPA brewed with English and American hops. A small batch brewed only once.","image_url":"https://images.punkapi.com/v2/keg.png","abv":4.5,"ibu":60,"target_fg":1010,"target_og":1044,"ebc":20,"srm":10,"ph":4.4,"attenuation_level":75,"volume":{"value":20,"unit":"litres"},"boil_volume":{"value":25,"unit":"litres"},"method":{"mash_temp":[{"temp":{"value":64,"unit":"celsius"},"duration":75}],"fermentation":{"temp":{"value":19,"unit":"celsius"}},"twist":null},"ingredients":{"malt":[{"name":"Maris Otter Extra Pale","amount":{"value":3.3,"unit":"kilograms"}},{"name":"Caramalt","amount":{"value":0.2,"unit":"kilograms"}},{"name":"Munich","amount":{"value":0.4,"unit":"kilograms"}}],"hops":[{"name":"Fuggles","amount":{"value":25,"unit":"grams"},"add":"start","attribute":"bitter"},{"name":"First Gold","amount":{"value":25,"unit":"grams"},"add":"start","attribute":"bitter"},{'

####  Checking the response

In [4]:
resp

####  Printing the dataset of first 5 rows

In [5]:
df.head()

,id,name,tagline,first_brewed,description,image_url,abv,ibu,target_fg,target_og,...,srm,ph,attenuation_level,volume,boil_volume,method,ingredients,food_pairing,brewers_tips,contributed_by
0,1,Buzz,A Real Bitter Experience.,09/2007,"A light, crisp and bitter IPA brewed with Engl...",https://images.punkapi.com/v2/keg.png,4.5,60.0,1010,1044.0,...,10.0,4.4,75.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 64, 'unit': ...","{'malt': [{'name': 'Maris Otter Extra Pale', '...","[Spicy chicken tikka masala, Grilled chicken q...",The earthy and floral aromas from the hops can...,Sam Mason <samjbmason>
1,2,Trashy Blonde,You Know You Shouldn't,04/2008,"A titillating, neurotic, peroxide punk of a Pa...",https://images.punkapi.com/v2/2.png,4.1,41.5,1010,1041.7,...,15.0,4.4,76.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 69, 'unit': ...","{'malt': [{'name': 'Maris Otter Extra Pale', '...","[Fresh crab with lemon, Garlic butter dipping ...",Be careful not to collect too much wort from t...,Sam Mason <samjbmason>
2,3,Berliner Weisse With Yuzu - B-Sides,Japanese Citrus Berliner Weisse.,11/2015,Japanese citrus fruit intensifies the sour nat...,https://images.punkapi.com/v2/keg.png,4.2,8.0,1007,1040.0,...,4.0,3.2,83.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 60, 'unit': ...","{'malt': [{'name': 'Propino Pale Malt', 'amoun...","[Smoked chicken wings, Miso ramen, Yuzu cheese...",Clean everything twice. All you want is the cl...,Sam Mason <samjbmason>
3,4,Pilsen Lager,Unleash the Yeast Series.,09/2013,Our Unleash the Yeast series was an epic exper...,https://images.punkapi.com/v2/4.png,6.3,55.0,1012,1060.0,...,15.0,4.4,80.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 65, 'unit': ...","{'malt': [{'name': 'Extra Pale', 'amount': {'v...","[Spicy crab cakes, Spicy cucumber and carrot T...",Play around with the fermentation temperature ...,Ali Skinner <AliSkinner>
4,5,Avery Brown Dredge,Bloggers' Imperial Pilsner.,02/2011,An Imperial Pilsner in collaboration with beer...,https://images.punkapi.com/v2/5.png,7.2,59.0,1027,1069.0,...,5.0,4.4,67.0,"{'value': 20, 'unit': 'litres'}","{'value': 25, 'unit': 'litres'}","{'mash_temp': [{'temp': {'value': 66, 'unit': ...","{'malt': [{'name': 'Lager Malt', 'amount': {'v...","[Vietnamese squid salad, Chargrilled corn on t...",Make sure you have a big enough yeast starter ...,Sam Mason <samjbmason>

####  Flatten the JSON

In [6]:
dic_flattened = [flatten(d) for d in txt]

In [7]:
dic_flattened[0]

{'id': 1,
 'name': 'Buzz',
 'tagline': 'A Real Bitter Experience.',
 'first_brewed': '09/2007',
 'description': 'A light, crisp and bitter IPA brewed with English and American hops. A small batch brewed only once.',
 'image_url': 'https://images.punkapi.com/v2/keg.png',
 'abv': 4.5,
 'ibu': 60,
 'target_fg': 1010,
 'target_og': 1044,
 'ebc': 20,
 'srm': 10,
 'ph': 4.4,
 'attenuation_level': 75,
 'volume_value': 20,
 'volume_unit': 'litres',
 'boil_volume_value': 25,
 'boil_volume_unit': 'litres',
 'method_mash_temp_0_temp_value': 64,
 'method_mash_temp_0_temp_unit': 'celsius',
 'method_mash_temp_0_duration': 75,
 'method_fermentation_temp_value': 19,
 'method_fermentation_temp_unit': 'celsius',
 'method_twist': None,
 'ingredients_malt_0_name': 'Maris Otter Extra Pale',
 'ingredients_malt_0_amount_value': 3.3,
 'ingredients_malt_0_amount_unit': 'kilograms',
 'ingredients_malt_1_name': 'Caramalt',
 'ingredients_malt_1_amount_value': 0.2,
 'ingredients_malt_1_amount_unit': 'kilograms',
 'ingredients_malt_2_name': 'Munich',
 'ingredients_malt_2_amount_value': 0.4,
 'ingredients_malt_2_amount_unit': 'kilograms',
 'ingredients_hops_0_name': 'Fuggles',
 'ingredients_hops_0_amount_value': 25,
 'ingredients_hops_0_amount_unit': 'grams',
 'ingredients_hops_0_add': 'start',
 'ingredients_hops_0_attribute': 'bitter',
 'ingredients_hops_1_name': 'First Gold',
 'ingredients_hops_1_amount_value': 25,
 'ingredients_hops_1_amount_unit': 'grams',
 'ingredients_hops_1_add': 'start',
 'ingredients_hops_1_attribute': 'bitter',
 'ingredients_hops_2_name': 'Fuggles',
 'ingredients_hops_2_amount_value': 37.5,
 'ingredients_hops_2_amount_unit': 'grams',
 'ingredients_hops_2_add': 'middle',
 'ingredients_hops_2_attribute': 'flavour',
 'ingredients_hops_3_name': 'First Gold',
 'ingredients_hops_3_amount_value': 37.5,
 'ingredients_hops_3_amount_unit': 'grams',
 'ingredients_hops_3_add': 'middle',
 'ingredients_hops_3_attribute': 'flavour',
 'ingredients_hops_4_name': 'Cascade',
 'ingredients_hops_4_amount_value': 37.5,
 'ingredients_hops_4_amount_unit': 'grams',
 'ingredients_hops_4_add': 'end',
 'ingredients_hops_4_attribute': 'flavour',
 'ingredients_yeast': 'Wyeast 1056 - American Ale™',
 'food_pairing_0': 'Spicy chicken tikka masala',
 'food_pairing_1': 'Grilled chicken quesadilla',
 'food_pairing_2': 'Caramel toffee cake',
 'brewers_tips': 'The earthy and floral aromas from the hops can be overpowering. Drop a little Cascade in at the end of the boil to lift the profile with a bit of citrus.',
 'contributed_by': 'Sam Mason <samjbmason>'}

####  Normalizing the data

In [8]:
from pandas import json_normalize
final_df = json_normalize(dic_flattened)
#final_df

####  After the normalization printing the dataset

In [9]:
final_df.head()

,id,name,tagline,first_brewed,description,image_url,abv,ibu,target_fg,target_og,...,ingredients_hops_9_name,ingredients_hops_9_amount_value,ingredients_hops_9_amount_unit,ingredients_hops_9_add,ingredients_hops_9_attribute,ingredients_hops_10_name,ingredients_hops_10_amount_value,ingredients_hops_10_amount_unit,ingredients_hops_10_add,ingredients_hops_10_attribute
0,1,Buzz,A Real Bitter Experience.,09/2007,"A light, crisp and bitter IPA brewed with Engl...",https://images.punkapi.com/v2/keg.png,4.5,60.0,1010,1044.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Trashy Blonde,You Know You Shouldn't,04/2008,"A titillating, neurotic, peroxide punk of a Pa...",https://images.punkapi.com/v2/2.png,4.1,41.5,1010,1041.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Berliner Weisse With Yuzu - B-Sides,Japanese Citrus Berliner Weisse.,11/2015,Japanese citrus fruit intensifies the sour nat...,https://images.punkapi.com/v2/keg.png,4.2,8.0,1007,1040.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Pilsen Lager,Unleash the Yeast Series.,09/2013,Our Unleash the Yeast series was an epic exper...,https://images.punkapi.com/v2/4.png,6.3,55.0,1012,1060.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Avery Brown Dredge,Bloggers' Imperial Pilsner.,02/2011,An Imperial Pilsner in collaboration with beer...,https://images.punkapi.com/v2/5.png,7.2,59.0,1027,1069.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
final_df.isnull().sum()

id                                   0
name                                 0
tagline                              0
first_brewed                         0
description                          0
                                    ..
ingredients_hops_10_name            24
ingredients_hops_10_amount_value    24
ingredients_hops_10_amount_unit     24
ingredients_hops_10_add             24
ingredients_hops_10_attribute       24
Length: 125, dtype: int64

####  Get column names from dataset

In [11]:
final_df.columns[:50].tolist()

['id',
 'name',
 'tagline',
 'first_brewed',
 'description',
 'image_url',
 'abv',
 'ibu',
 'target_fg',
 'target_og',
 'ebc',
 'srm',
 'ph',
 'attenuation_level',
 'volume_value',
 'volume_unit',
 'boil_volume_value',
 'boil_volume_unit',
 'method_mash_temp_0_temp_value',
 'method_mash_temp_0_temp_unit',
 'method_mash_temp_0_duration',
 'method_fermentation_temp_value',
 'method_fermentation_temp_unit',
 'method_twist',
 'ingredients_malt_0_name',
 'ingredients_malt_0_amount_value',
 'ingredients_malt_0_amount_unit',
 'ingredients_malt_1_name',
 'ingredients_malt_1_amount_value',
 'ingredients_malt_1_amount_unit',
 'ingredients_malt_2_name',
 'ingredients_malt_2_amount_value',
 'ingredients_malt_2_amount_unit',
 'ingredients_hops_0_name',
 'ingredients_hops_0_amount_value',
 'ingredients_hops_0_amount_unit',
 'ingredients_hops_0_add',
 'ingredients_hops_0_attribute',
 'ingredients_hops_1_name',
 'ingredients_hops_1_amount_value',
 'ingredients_hops_1_amount_unit',
 'ingredients_hops_1_add',
 'ingredients_hops_1_attribute',
 'ingredients_hops_2_name',
 'ingredients_hops_2_amount_value',
 'ingredients_hops_2_amount_unit',
 'ingredients_hops_2_add',
 'ingredients_hops_2_attribute',
 'ingredients_hops_3_name',
 'ingredients_hops_3_amount_value']

####  Open the file for writing

In [12]:
with open('file.txt','w') as file:
    for i in final_df.columns[:].tolist():
        file.write("\n"+i)

####  Printing the total columns in the dataset

In [13]:
final_df.columns[:].tolist()

['id',
 'name',
 'tagline',
 'first_brewed',
 'description',
 'image_url',
 'abv',
 'ibu',
 'target_fg',
 'target_og',
 'ebc',
 'srm',
 'ph',
 'attenuation_level',
 'volume_value',
 'volume_unit',
 'boil_volume_value',
 'boil_volume_unit',
 'method_mash_temp_0_temp_value',
 'method_mash_temp_0_temp_unit',
 'method_mash_temp_0_duration',
 'method_fermentation_temp_value',
 'method_fermentation_temp_unit',
 'method_twist',
 'ingredients_malt_0_name',
 'ingredients_malt_0_amount_value',
 'ingredients_malt_0_amount_unit',
 'ingredients_malt_1_name',
 'ingredients_malt_1_amount_value',
 'ingredients_malt_1_amount_unit',
 'ingredients_malt_2_name',
 'ingredients_malt_2_amount_value',
 'ingredients_malt_2_amount_unit',
 'ingredients_hops_0_name',
 'ingredients_hops_0_amount_value',
 'ingredients_hops_0_amount_unit',
 'ingredients_hops_0_add',
 'ingredients_hops_0_attribute',
 'ingredients_hops_1_name',
 'ingredients_hops_1_amount_value',
 'ingredients_hops_1_amount_unit',
 'ingredients_hops_1_add',
 'ingredients_hops_1_attribute',
 'ingredients_hops_2_name',
 'ingredients_hops_2_amount_value',
 'ingredients_hops_2_amount_unit',
 'ingredients_hops_2_add',
 'ingredients_hops_2_attribute',
 'ingredients_hops_3_name',
 'ingredients_hops_3_amount_value',
 'ingredients_hops_3_amount_unit',
 'ingredients_hops_3_add',
 'ingredients_hops_3_attribute',
 'ingredients_hops_4_name',
 'ingredients_hops_4_amount_value',
 'ingredients_hops_4_amount_unit',
 'ingredients_hops_4_add',
 'ingredients_hops_4_attribute',
 'ingredients_yeast',
 'food_pairing_0',
 'food_pairing_1',
 'food_pairing_2',
 'brewers_tips',
 'contributed_by',
 'food_pairing_3',
 'method_mash_temp_1_temp_value',
 'method_mash_temp_1_temp_unit',
 'method_mash_temp_1_duration',
 'method_mash_temp_2_temp_value',
 'method_mash_temp_2_temp_unit',
 'method_mash_temp_2_duration',
 'method_mash_temp_3_temp_value',
 'method_mash_temp_3_temp_unit',
 'method_mash_temp_3_duration',
 'ingredients_malt_3_name',
 'ingredients_malt_3_amount_value',
 'ingredients_malt_3_amount_unit',
 'ingredients_hops_5_name',
 'ingredients_hops_5_amount_value',
 'ingredients_hops_5_amount_unit',
 'ingredients_hops_5_add',
 'ingredients_hops_5_attribute',
 'ingredients_hops_6_name',
 'ingredients_hops_6_amount_value',
 'ingredients_hops_6_amount_unit',
 'ingredients_hops_6_add',
 'ingredients_hops_6_attribute',
 'ingredients_hops_7_name',
 'ingredients_hops_7_amount_value',
 'ingredients_hops_7_amount_unit',
 'ingredients_hops_7_add',
 'ingredients_hops_7_attribute',
 'ingredients_hops_8_name',
 'ingredients_hops_8_amount_value',
 'ingredients_hops_8_amount_unit',
 'ingredients_hops_8_add',
 'ingredients_hops_8_attribute',
 'ingredients_malt_4_name',
 'ingredients_malt_4_amount_value',
 'ingredients_malt_4_amount_unit',
 'ingredients_malt_5_name',
 'ingredients_malt_5_amount_value',
 'ingredients_malt_5_amount_unit',
 'ingredients_malt_6_name',
 'ingredients_malt_6_amount_value',
 'ingredients_malt_6_amount_unit',
 'ingredients_malt_7_name',
 'ingredients_malt_7_amount_value',
 'ingredients_malt_7_amount_unit',
 'ingredients_malt_8_name',
 'ingredients_malt_8_amount_value',
 'ingredients_malt_8_amount_unit',
 'ingredients_malt_9_name',
 'ingredients_malt_9_amount_value',
 'ingredients_malt_9_amount_unit',
 'ingredients_hops_9_name',
 'ingredients_hops_9_amount_value',
 'ingredients_hops_9_amount_unit',
 'ingredients_hops_9_add',
 'ingredients_hops_9_attribute',
 'ingredients_hops_10_name',
 'ingredients_hops_10_amount_value',
 'ingredients_hops_10_amount_unit',
 'ingredients_hops_10_add',
 'ingredients_hops_10_attribute']

####  Dividing the columns based on different categories of beers

In [14]:
drinks_df = final_df[['id',
 'name',
 'tagline',
 'first_brewed',
 'description',
 'image_url',
 'abv',
 'ibu',
 'target_fg',
 'target_og',
 'ebc',
 'srm',
 'ph',
 'attenuation_level',
 'volume_value',
 'volume_unit',
 'boil_volume_value',
 'boil_volume_unit',
 'brewers_tips',
 'contributed_by']]

methods_df = final_df[[ 'id', 'name',
 'method_mash_temp_0_temp_value',
 'method_mash_temp_0_temp_unit',
 'method_mash_temp_0_duration',
 'method_fermentation_temp_value',
 'method_fermentation_temp_unit',
 'method_twist',
 'method_mash_temp_1_temp_value',
 'method_mash_temp_1_temp_unit',
 'method_mash_temp_1_duration',
 'method_mash_temp_2_temp_value',
 'method_mash_temp_2_temp_unit',
 'method_mash_temp_2_duration',
 'method_mash_temp_3_temp_value',
 'method_mash_temp_3_temp_unit',
 'method_mash_temp_3_duration']]

food_pairing_df = final_df[['id',
  'name',
 'food_pairing_0',
 'food_pairing_1',
 'food_pairing_2',
 'food_pairing_3']]

ingredients_df = final_df[['id',
  'name',
 'ingredients_malt_0_name',
 'ingredients_malt_0_amount_value',
 'ingredients_malt_0_amount_unit',
 'ingredients_malt_1_name',
 'ingredients_malt_1_amount_value',
 'ingredients_malt_1_amount_unit',
 'ingredients_malt_2_name',
 'ingredients_malt_2_amount_value',
 'ingredients_malt_2_amount_unit',
 'ingredients_hops_0_name',
 'ingredients_hops_0_amount_value',
 'ingredients_hops_0_amount_unit',
 'ingredients_hops_0_add',
 'ingredients_hops_0_attribute',
 'ingredients_hops_1_name',
 'ingredients_hops_1_amount_value',
 'ingredients_hops_1_amount_unit',
 'ingredients_hops_1_add',
 'ingredients_hops_1_attribute',
 'ingredients_hops_2_name',
 'ingredients_hops_2_amount_value',
 'ingredients_hops_2_amount_unit',
 'ingredients_hops_2_add',
 'ingredients_hops_2_attribute',
 'ingredients_hops_3_name',
 'ingredients_hops_3_amount_value',
 'ingredients_hops_3_amount_unit',
 'ingredients_hops_3_add',
 'ingredients_hops_3_attribute',
 'ingredients_hops_4_name',
 'ingredients_hops_4_amount_value',
 'ingredients_hops_4_amount_unit',
 'ingredients_hops_4_add',
 'ingredients_hops_4_attribute',
 'ingredients_malt_3_name',
 'ingredients_malt_3_amount_value',
 'ingredients_malt_3_amount_unit',
 'ingredients_hops_5_name',
 'ingredients_hops_5_amount_value',
 'ingredients_hops_5_amount_unit',
 'ingredients_hops_5_add',
 'ingredients_hops_5_attribute',
 'ingredients_hops_6_name',
 'ingredients_hops_6_amount_value',
 'ingredients_hops_6_amount_unit',
 'ingredients_hops_6_add',
 'ingredients_hops_6_attribute',
 'ingredients_hops_7_name',
 'ingredients_hops_7_amount_value',
 'ingredients_hops_7_amount_unit',
 'ingredients_hops_7_add',
 'ingredients_hops_7_attribute',
 'ingredients_hops_8_name',
 'ingredients_hops_8_amount_value',
 'ingredients_hops_8_amount_unit',
 'ingredients_hops_8_add',
 'ingredients_hops_8_attribute',
 'ingredients_malt_4_name',
 'ingredients_malt_4_amount_value',
 'ingredients_malt_4_amount_unit',
 'ingredients_malt_5_name',
 'ingredients_malt_5_amount_value',
 'ingredients_malt_5_amount_unit',
 'ingredients_malt_6_name',
 'ingredients_malt_6_amount_value',
 'ingredients_malt_6_amount_unit',
 'ingredients_malt_7_name',
 'ingredients_malt_7_amount_value',
 'ingredients_malt_7_amount_unit',
 'ingredients_malt_8_name',
 'ingredients_malt_8_amount_value',
 'ingredients_malt_8_amount_unit',
 'ingredients_malt_9_name',
 'ingredients_malt_9_amount_value',
 'ingredients_malt_9_amount_unit',
 'ingredients_hops_9_name',
 'ingredients_hops_9_amount_value',
 'ingredients_hops_9_amount_unit',
 'ingredients_hops_9_add',
 'ingredients_hops_9_attribute',
 'ingredients_hops_10_name',
 'ingredients_hops_10_amount_value',
 'ingredients_hops_10_amount_unit',
 'ingredients_hops_10_add',
 'ingredients_hops_10_attribute',
 'ingredients_yeast']]

####  Datasets into excel

In [15]:
with pd.ExcelWriter("drinks_df.xlsx") as writer:
     drinks_df.to_excel(writer)

with pd.ExcelWriter("methods_df.xlsx") as writer:
     methods_df.to_excel(writer)

with pd.ExcelWriter("ingredients_df.xlsx") as writer:
     ingredients_df.to_excel(writer)
        #print('mixing_new_df.xlsx')
        
with pd.ExcelWriter("food_pairing_df.xlsx") as writer:
     food_pairing_df.to_excel(writer)

In [16]:
#mixing_new_df.head()

####  Printing the drinks dataset

In [17]:
drinks_df.head()

,id,name,tagline,first_brewed,description,image_url,abv,ibu,target_fg,target_og,ebc,srm,ph,attenuation_level,volume_value,volume_unit,boil_volume_value,boil_volume_unit,brewers_tips,contributed_by
0,1,Buzz,A Real Bitter Experience.,09/2007,"A light, crisp and bitter IPA brewed with Engl...",https://images.punkapi.com/v2/keg.png,4.5,60.0,1010,1044.0,20.0,10.0,4.4,75.0,20,litres,25,litres,The earthy and floral aromas from the hops can...,Sam Mason <samjbmason>
1,2,Trashy Blonde,You Know You Shouldn't,04/2008,"A titillating, neurotic, peroxide punk of a Pa...",https://images.punkapi.com/v2/2.png,4.1,41.5,1010,1041.7,15.0,15.0,4.4,76.0,20,litres,25,litres,Be careful not to collect too much wort from t...,Sam Mason <samjbmason>
2,3,Berliner Weisse With Yuzu - B-Sides,Japanese Citrus Berliner Weisse.,11/2015,Japanese citrus fruit intensifies the sour nat...,https://images.punkapi.com/v2/keg.png,4.2,8.0,1007,1040.0,8.0,4.0,3.2,83.0,20,litres,25,litres,Clean everything twice. All you want is the cl...,Sam Mason <samjbmason>
3,4,Pilsen Lager,Unleash the Yeast Series.,09/2013,Our Unleash the Yeast series was an epic exper...,https://images.punkapi.com/v2/4.png,6.3,55.0,1012,1060.0,30.0,15.0,4.4,80.0,20,litres,25,litres,Play around with the fermentation temperature ...,Ali Skinner <AliSkinner>
4,5,Avery Brown Dredge,Bloggers' Imperial Pilsner.,02/2011,An Imperial Pilsner in collaboration with beer...,https://images.punkapi.com/v2/5.png,7.2,59.0,1027,1069.0,10.0,5.0,4.4,67.0,20,litres,25,litres,Make sure you have a big enough yeast starter ...,Sam Mason <samjbmason>

####  Arranging the date format in the correct order

In [18]:
drinks_df['first_brewed']=pd.to_datetime(drinks_df['first_brewed'],format="%m/%Y")

/tmp/ipykernel_21623/3916719396.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drinks_df['first_brewed']=pd.to_datetime(drinks_df['first_brewed'],format="%m/%Y")

In [19]:
drinks_df.head()

,id,name,tagline,first_brewed,description,image_url,abv,ibu,target_fg,target_og,ebc,srm,ph,attenuation_level,volume_value,volume_unit,boil_volume_value,boil_volume_unit,brewers_tips,contributed_by
0,1,Buzz,A Real Bitter Experience.,2007-09-01,"A light, crisp and bitter IPA brewed with Engl...",https://images.punkapi.com/v2/keg.png,4.5,60.0,1010,1044.0,20.0,10.0,4.4,75.0,20,litres,25,litres,The earthy and floral aromas from the hops can...,Sam Mason <samjbmason>
1,2,Trashy Blonde,You Know You Shouldn't,2008-04-01,"A titillating, neurotic, peroxide punk of a Pa...",https://images.punkapi.com/v2/2.png,4.1,41.5,1010,1041.7,15.0,15.0,4.4,76.0,20,litres,25,litres,Be careful not to collect too much wort from t...,Sam Mason <samjbmason>
2,3,Berliner Weisse With Yuzu - B-Sides,Japanese Citrus Berliner Weisse.,2015-11-01,Japanese citrus fruit intensifies the sour nat...,https://images.punkapi.com/v2/keg.png,4.2,8.0,1007,1040.0,8.0,4.0,3.2,83.0,20,litres,25,litres,Clean everything twice. All you want is the cl...,Sam Mason <samjbmason>
3,4,Pilsen Lager,Unleash the Yeast Series.,2013-09-01,Our Unleash the Yeast series was an epic exper...,https://images.punkapi.com/v2/4.png,6.3,55.0,1012,1060.0,30.0,15.0,4.4,80.0,20,litres,25,litres,Play around with the fermentation temperature ...,Ali Skinner <AliSkinner>
4,5,Avery Brown Dredge,Bloggers' Imperial Pilsner.,2011-02-01,An Imperial Pilsner in collaboration with beer...,https://images.punkapi.com/v2/5.png,7.2,59.0,1027,1069.0,10.0,5.0,4.4,67.0,20,litres,25,litres,Make sure you have a big enough yeast starter ...,Sam Mason <samjbmason>

####  Replacing the nan values with '0'

In [20]:
drinks_df.replace({np.inf: np.nan, -np.inf: np.nan}, inplace=True)
drinks_df = drinks_df.fillna(0)
drinks_df.head()

/tmp/ipykernel_21623/4087449799.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drinks_df.replace({np.inf: np.nan, -np.inf: np.nan}, inplace=True)

,id,name,tagline,first_brewed,description,image_url,abv,ibu,target_fg,target_og,ebc,srm,ph,attenuation_level,volume_value,volume_unit,boil_volume_value,boil_volume_unit,brewers_tips,contributed_by
0,1,Buzz,A Real Bitter Experience.,2007-09-01,"A light, crisp and bitter IPA brewed with Engl...",https://images.punkapi.com/v2/keg.png,4.5,60.0,1010,1044.0,20.0,10.0,4.4,75.0,20,litres,25,litres,The earthy and floral aromas from the hops can...,Sam Mason <samjbmason>
1,2,Trashy Blonde,You Know You Shouldn't,2008-04-01,"A titillating, neurotic, peroxide punk of a Pa...",https://images.punkapi.com/v2/2.png,4.1,41.5,1010,1041.7,15.0,15.0,4.4,76.0,20,litres,25,litres,Be careful not to collect too much wort from t...,Sam Mason <samjbmason>
2,3,Berliner Weisse With Yuzu - B-Sides,Japanese Citrus Berliner Weisse.,2015-11-01,Japanese citrus fruit intensifies the sour nat...,https://images.punkapi.com/v2/keg.png,4.2,8.0,1007,1040.0,8.0,4.0,3.2,83.0,20,litres,25,litres,Clean everything twice. All you want is the cl...,Sam Mason <samjbmason>
3,4,Pilsen Lager,Unleash the Yeast Series.,2013-09-01,Our Unleash the Yeast series was an epic exper...,https://images.punkapi.com/v2/4.png,6.3,55.0,1012,1060.0,30.0,15.0,4.4,80.0,20,litres,25,litres,Play around with the fermentation temperature ...,Ali Skinner <AliSkinner>
4,5,Avery Brown Dredge,Bloggers' Imperial Pilsner.,2011-02-01,An Imperial Pilsner in collaboration with beer...,https://images.punkapi.com/v2/5.png,7.2,59.0,1027,1069.0,10.0,5.0,4.4,67.0,20,litres,25,litres,Make sure you have a big enough yeast starter ...,Sam Mason <samjbmason>

####  Printing the methods dataset

In [21]:
methods_df.head()

,id,name,method_mash_temp_0_temp_value,method_mash_temp_0_temp_unit,method_mash_temp_0_duration,method_fermentation_temp_value,method_fermentation_temp_unit,method_twist,method_mash_temp_1_temp_value,method_mash_temp_1_temp_unit,method_mash_temp_1_duration,method_mash_temp_2_temp_value,method_mash_temp_2_temp_unit,method_mash_temp_2_duration,method_mash_temp_3_temp_value,method_mash_temp_3_temp_unit,method_mash_temp_3_duration
0,1,Buzz,64,celsius,75.0,19,celsius,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Trashy Blonde,69,celsius,NaN,18,celsius,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,Berliner Weisse With Yuzu - B-Sides,60,celsius,10.0,21,celsius,Soured naturally using the kettle souring tech...,65.0,celsius,30.0,72.0,celsius,10.0,78.0,celsius,5.0
3,4,Pilsen Lager,65,celsius,NaN,9,celsius,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Avery Brown Dredge,66,celsius,70.0,10,celsius,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

####  Replacing nan values with '0'

In [22]:
methods_df.replace({np.inf: np.nan, -np.inf: np.nan}, inplace=True)
methods_df = methods_df.fillna(0)
methods_df.head()

/tmp/ipykernel_21623/4029621459.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  methods_df.replace({np.inf: np.nan, -np.inf: np.nan}, inplace=True)

,id,name,method_mash_temp_0_temp_value,method_mash_temp_0_temp_unit,method_mash_temp_0_duration,method_fermentation_temp_value,method_fermentation_temp_unit,method_twist,method_mash_temp_1_temp_value,method_mash_temp_1_temp_unit,method_mash_temp_1_duration,method_mash_temp_2_temp_value,method_mash_temp_2_temp_unit,method_mash_temp_2_duration,method_mash_temp_3_temp_value,method_mash_temp_3_temp_unit,method_mash_temp_3_duration
0,1,Buzz,64,celsius,75.0,19,celsius,0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0
1,2,Trashy Blonde,69,celsius,0.0,18,celsius,0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0
2,3,Berliner Weisse With Yuzu - B-Sides,60,celsius,10.0,21,celsius,Soured naturally using the kettle souring tech...,65.0,celsius,30.0,72.0,celsius,10.0,78.0,celsius,5.0
3,4,Pilsen Lager,65,celsius,0.0,9,celsius,0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0
4,5,Avery Brown Dredge,66,celsius,70.0,10,celsius,0,0.0,0,0.0,0.0,0,0.0,0.0,0,0.0

####  Printing the food pairing dataset

In [23]:
food_pairing_df.head()

,id,name,food_pairing_0,food_pairing_1,food_pairing_2,food_pairing_3
0,1,Buzz,Spicy chicken tikka masala,Grilled chicken quesadilla,Caramel toffee cake,NaN
1,2,Trashy Blonde,Fresh crab with lemon,Garlic butter dipping sauce,Goats cheese salad,Creamy lemon bar doused in powdered sugar
2,3,Berliner Weisse With Yuzu - B-Sides,Smoked chicken wings,Miso ramen,Yuzu cheesecake,NaN
3,4,Pilsen Lager,Spicy crab cakes,Spicy cucumber and carrot Thai salad,Sweet filled dumplings,NaN
4,5,Avery Brown Dredge,Vietnamese squid salad,Chargrilled corn on the cob with paprika butter,Strawberry and rhubarb pie,NaN

####  Replacing the nan values with '0'

In [24]:
food_pairing_df.replace({np.inf: np.nan, -np.inf: np.nan}, inplace=True)
food_pairing_df = food_pairing_df.fillna(0)
food_pairing_df.head()

/tmp/ipykernel_21623/1343969754.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  food_pairing_df.replace({np.inf: np.nan, -np.inf: np.nan}, inplace=True)

,id,name,food_pairing_0,food_pairing_1,food_pairing_2,food_pairing_3
0,1,Buzz,Spicy chicken tikka masala,Grilled chicken quesadilla,Caramel toffee cake,0
1,2,Trashy Blonde,Fresh crab with lemon,Garlic butter dipping sauce,Goats cheese salad,Creamy lemon bar doused in powdered sugar
2,3,Berliner Weisse With Yuzu - B-Sides,Smoked chicken wings,Miso ramen,Yuzu cheesecake,0
3,4,Pilsen Lager,Spicy crab cakes,Spicy cucumber and carrot Thai salad,Sweet filled dumplings,0
4,5,Avery Brown Dredge,Vietnamese squid salad,Chargrilled corn on the cob with paprika butter,Strawberry and rhubarb pie,0

####  Melting Ingredients from the flattened format of JSON to denormalised format

In [25]:
#Gather columns into rows
melted_ingredients_df = pd.melt(ingredients_df,                  
  id_vars=["id", "name"])
  

mixing_df =melted_ingredients_df.dropna()
mixing_df.head()

,id,name,variable,value
0,1,Buzz,ingredients_malt_0_name,Maris Otter Extra Pale
1,2,Trashy Blonde,ingredients_malt_0_name,Maris Otter Extra Pale
2,3,Berliner Weisse With Yuzu - B-Sides,ingredients_malt_0_name,Propino Pale Malt
3,4,Pilsen Lager,ingredients_malt_0_name,Extra Pale
4,5,Avery Brown Dredge,ingredients_malt_0_name,Lager Malt

####  Rename the variable column into ingredients

In [26]:
mixing_df.rename(columns={'variable':'ingredients'},inplace=True) 
#mixing_df.count()
mixing_df.head()

/tmp/ipykernel_21623/3137992260.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  mixing_df.rename(columns={'variable':'ingredients'},inplace=True)

,id,name,ingredients,value
0,1,Buzz,ingredients_malt_0_name,Maris Otter Extra Pale
1,2,Trashy Blonde,ingredients_malt_0_name,Maris Otter Extra Pale
2,3,Berliner Weisse With Yuzu - B-Sides,ingredients_malt_0_name,Propino Pale Malt
3,4,Pilsen Lager,ingredients_malt_0_name,Extra Pale
4,5,Avery Brown Dredge,ingredients_malt_0_name,Lager Malt

#### Loading the data into database

In [27]:
def db_connector():

    conn = pyodbc.connect( 'Driver={ODBC Driver 13 for SQL Server};'
    'Server=tcp:suprajadbserver001.database.windows.net,1433;'
    'Database=suprajapdaSQLdb001;'
    'Uid=azuser001;'
    'Pwd=Supraja@04071993;'
    'Encrypt=yes;'
    'TrustServerCertificate=no;'
    'Connection Timeout=30;')
        

    #cursor = conn.cursor()
    cursor = conn.cursor()
    cursor.execute("truncate table dbo.mixing;")
    
    for index,row in mixing_df.iterrows():
        
        cursor.execute("""INSERT INTO dbo.mixing(Id, [Name], Variable, [value]) 
                         values (?,?,?,?)"""
                                          , row['id'], 
                                            row['name'], 
                                             row['ingredients'],
                                            row['value']) 
        #print(type(row))
        conn.commit()
        
        
    cursor.execute("truncate table dbo.drinks;") 

    for index,row in drinks_df.iterrows():
        cursor.execute("""INSERT INTO dbo.drinks(Id, [Name], tagline, first_brewed,[description],image_url,abv,ibu,target_fg,target_og,ebc,srm,ph,attenuation_level,volume_value,volume_unit,
                          boil_volume_value,boil_volume_unit,brewers_tips,contributed_by) 
                         values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"""
                                          , row['id'], 
                                            row['name'], 
                                            row['tagline'],
                                            row['first_brewed'],
                                            row['description'],
                                            row['image_url'],
                                            row['abv'],
                                            row['ibu'],
                                            row['target_fg'],
                                            row['target_og'],
                                            row['ebc'],
                                            row['srm'],
                                            row['ph'],
                                            row['attenuation_level'],
                                            row['volume_value'],
                                            row['volume_unit'],
                                            row['boil_volume_value'],
                                            row['boil_volume_unit'],
                                            row['brewers_tips'],
                                            row['contributed_by']) 
        #print(type(row))
        conn.commit()
    cursor.execute("truncate table dbo.methods;")
    
    for index,row in methods_df.iterrows():
        
        cursor.execute("""INSERT INTO dbo.methods(Id, [Name],method_mash_temp_0_temp_value,method_mash_temp_0_temp_unit,method_mash_temp_0_duration,method_fermentation_temp_value,
                          method_fermentation_temp_unit,method_twist,method_mash_temp_1_temp_value,method_mash_temp_1_temp_unit,method_mash_temp_1_duration,
                          method_mash_temp_2_temp_value,method_mash_temp_2_temp_unit,method_mash_temp_2_duration,method_mash_temp_3_temp_value,method_mash_temp_3_temp_unit,
                          method_mash_temp_3_duration) 
                          values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"""
                                          , row['id'], 
                                            row['name'], 
                                            row['method_mash_temp_0_temp_value'],
                                            row['method_mash_temp_0_temp_unit'],
                                            row['method_mash_temp_0_duration'],
                                            row['method_fermentation_temp_value'],
                                            row['method_fermentation_temp_unit'],
                                            row['method_twist'],
                                            row['method_mash_temp_1_temp_value'],
                                            row['method_mash_temp_1_temp_unit'],
                                            row['method_mash_temp_1_duration'],
                                            row['method_mash_temp_2_temp_value'],
                                            row['method_mash_temp_2_temp_unit'],
                                            row['method_mash_temp_2_duration'], 
                                            row['method_mash_temp_3_temp_value'],
                                            row['method_mash_temp_3_temp_unit'],
                                            row['method_mash_temp_3_duration']) 
        #print(type(row))
        conn.commit()
    cursor.execute("truncate table dbo.food_pairing;")
    
    for index,row in food_pairing_df.iterrows():
        
        cursor.execute("""INSERT INTO dbo.food_pairing(Id,[Name],food_pairing_0,food_pairing_1,food_pairing_2,food_pairing_3) 
                         values (?,?,?,?,?,?)"""
                                          , row['id'], 
                                            row['name'], 
                                            row['food_pairing_0'],
                                            row['food_pairing_1'],
                                            row['food_pairing_2'],
                                            row['food_pairing_3']) 
        #print(type(row))
        conn.commit()
        
        
        
    cursor.close()
    conn.close()
  #  sql_query = pd.read_sql_query('SELECT * FROM dbo.Customers',conn)
#     print(sql_query)
#     print(type(sql_query))

db_connector()

In [125]:
import pyodbc
import pandas as pd
# Some other example server values are
# server = 'localhost\sqlexpress' # for a named instance
# server = 'myserver,port' # to specify an alternate port
server = 'tcp:suprajadbserver001.database.windows.net,1433' 
database = 'suprajapdaSQLdb001' 
username = 'azuser001' 
password = 'Supraja@04071993'  
cnxn = pyodbc.connect('DRIVER={ODBC Driver 13 for SQL Server};SERVER='+server+';DATABASE='+database+';UID='+username+';PWD='+ password)
cursor = cnxn.cursor()
# select 26 rows from SQL table to insert in dataframe.

df = pd.read_sql('''select distinct Id, [Name], tagline, first_brewed,[description],image_url,abv,ibu,target_fg,target_og,ebc,srm,ph,attenuation_level,volume_value,volume_unit,
boil_volume_value,boil_volume_unit,brewers_tips,contributed_by, 
method_mash_temp_0_temp_value,
method_mash_temp_0_temp_unit,
method_mash_temp_0_duration,
method_fermentation_temp_value,
method_fermentation_temp_unit,
method_twist,
method_mash_temp_1_temp_value,
method_mash_temp_1_temp_unit,
method_mash_temp_1_duration,
method_mash_temp_2_temp_value,
method_mash_temp_2_temp_unit,
method_mash_temp_2_duration,
method_mash_temp_3_temp_value,
method_mash_temp_3_temp_unit,
method_mash_temp_3_duration,

food_pairing_0,
food_pairing_1,food_pairing_2,
food_pairing_3 from dbo.fact_drinks''', cnxn)
#print(df.head(6))
#print(df.columns.values)
pd.set_option('display.max_columns',None)
df.head()

/home/azuser001/anaconda3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(

,Id,Name,tagline,first_brewed,description,image_url,abv,ibu,target_fg,target_og,ebc,srm,ph,attenuation_level,volume_value,volume_unit,boil_volume_value,boil_volume_unit,brewers_tips,contributed_by,method_mash_temp_0_temp_value,method_mash_temp_0_temp_unit,method_mash_temp_0_duration,method_fermentation_temp_value,method_fermentation_temp_unit,method_twist,method_mash_temp_1_temp_value,method_mash_temp_1_temp_unit,method_mash_temp_1_duration,method_mash_temp_2_temp_value,method_mash_temp_2_temp_unit,method_mash_temp_2_duration,method_mash_temp_3_temp_value,method_mash_temp_3_temp_unit,method_mash_temp_3_duration,food_pairing_0,food_pairing_1,food_pairing_2,food_pairing_3
0,1,Buzz,A Real Bitter Experience.,2007-09-01,"A light, crisp and bitter IPA brewed with Engl...",https://images.punkapi.com/v2/keg.png,4.5,60.0,1010,1044.0,20.0,10.0,4.4,75.0,20,litres,25,litres,The earthy and floral aromas from the hops can...,Sam Mason <samjbmason>,64,celsius,75,19,celsius,0,0,0,0,0,0,0,0,0,0,Spicy chicken tikka masala,Grilled chicken quesadilla,Caramel toffee cake,0
1,10,Bramling X,Single Hop IPA Series - 2011.,2011-01-01,"Good old Bramling Cross is elegant, refined, a...",https://images.punkapi.com/v2/10.png,7.5,75.0,1013,1068.0,22.0,11.0,4.4,80.9,20,litres,25,litres,Getting good Bramling Cross is key. Most Engli...,Sam Mason <samjbmason>,65,celsius,75,19,celsius,0,0,0,0,0,0,0,0,0,0,Warm blackberry pie,Vinegar doused fish and chips,Aromatic korma curry with lemon and garlic naan,0
2,11,Misspent Youth,Milk & Honey Scotch Ale.,2013-04-01,"The brainchild of our small batch brewer, Geor...",https://images.punkapi.com/v2/keg.png,7.3,30.0,1020,1079.0,120.0,60.0,4.4,74.7,20,litres,25,litres,"Lots of malt in this one. Mash-in in stages, a...",Sam Mason <samjbmason>,67,celsius,75,19,celsius,See honey and lactose additions,0,0,0,0,0,0,0,0,0,Roasted garlic and chilli infused camembert ch...,Korean style chicken wings,Chocolate milk shake,0
3,12,Arcade Nation,Seasonal Black IPA.,2015-12-01,Running the knife-edge between an India Pale A...,https://images.punkapi.com/v2/12.png,5.3,60.0,1012,1052.0,200.0,100.0,4.2,77.0,20,litres,25,litres,Be as accurate as possible when weighing out y...,Sam Mason <samjbmason>,65,celsius,0,19,celsius,0,0,0,0,0,0,0,0,0,0,King prawn kebabs,Halibut with a mango and tomato salad,Mint chocloate ice cream,0
4,13,Movember,Moustache-Worthy Beer.,2009-11-01,"A deliciously robust, black malted beer with a...",https://images.punkapi.com/v2/13.png,4.5,50.0,1012,1047.0,140.0,70.0,5.2,74.5,20,litres,25,litres,"If you can’t find really fresh cascade, substi...",Sam Mason <samjbmason>,68,celsius,50,19,celsius,0,0,0,0,0,0,0,0,0,0,Vegetable egg scramble,Margherita pizza,Fresh berry crisp tart,0

In [30]:
df.duplicated().sum()

0

In [31]:
df.isnull().sum()

Id                                0
Name                              0
tagline                           0
first_brewed                      0
description                       0
image_url                         0
abv                               0
ibu                               0
target_fg                         0
target_og                         0
ebc                               0
srm                               0
ph                                0
attenuation_level                 0
volume_value                      0
volume_unit                       0
boil_volume_value                 0
boil_volume_unit                  0
brewers_tips                      0
contributed_by                    0
method_mash_temp_0_temp_value     0
method_mash_temp_0_temp_unit      0
method_mash_temp_0_duration       0
method_fermentation_temp_value    0
method_fermentation_temp_unit     0
method_twist                      0
method_mash_temp_1_temp_value     0
method_mash_temp_1_temp_unit      0
method_mash_temp_1_duration       0
method_mash_temp_2_temp_value     0
method_mash_temp_2_temp_unit      0
method_mash_temp_2_duration       0
method_mash_temp_3_temp_value     0
method_mash_temp_3_temp_unit      0
method_mash_temp_3_duration       0
food_pairing_0                    0
food_pairing_1                    0
food_pairing_2                    0
food_pairing_3                    0
dtype: int64

#### 1.How many beers have a ph level lessthan 3?

In [124]:
sp=df[df['ph']<3].shape
sp[0]

1

#### 2.Arrange the data into ascending order by first_brewed

In [123]:
df=df.sort_values(by=['first_brewed'], ascending=True)
df.head()

,Id,Name,tagline,first_brewed,description,image_url,abv,ibu,target_fg,target_og,ebc,srm,ph,attenuation_level,volume_value,volume_unit,boil_volume_value,boil_volume_unit,brewers_tips,contributed_by,method_mash_temp_0_temp_value,method_mash_temp_0_temp_unit,method_mash_temp_0_duration,method_fermentation_temp_value,method_fermentation_temp_unit,method_twist,method_mash_temp_1_temp_value,method_mash_temp_1_temp_unit,method_mash_temp_1_duration,method_mash_temp_2_temp_value,method_mash_temp_2_temp_unit,method_mash_temp_2_duration,method_mash_temp_3_temp_value,method_mash_temp_3_temp_unit,method_mash_temp_3_duration,food_pairing_0,food_pairing_1,food_pairing_2,food_pairing_3
0,1,Buzz,A Real Bitter Experience.,2007-09-01,"A light, crisp and bitter IPA brewed with Engl...",https://images.punkapi.com/v2/keg.png,4.5,60.0,1010,1044.0,20.0,10.0,4.4,75.0,20,litres,25,litres,The earthy and floral aromas from the hops can...,Sam Mason <samjbmason>,64,celsius,75,19,celsius,0,0,0,0,0,0,0,0,0,0,Spicy chicken tikka masala,Grilled chicken quesadilla,Caramel toffee cake,0
15,23,Storm,Islay Whisky Aged IPA.,2007-12-01,Dark and powerful Islay magic infuses this tro...,https://images.punkapi.com/v2/23.png,8.0,60.0,1010,1082.0,12.0,6.0,4.4,86.0,20,litres,25,litres,"After primary fermentation is complete, rack o...",Sam Mason <samjbmason>,65,celsius,75,19,celsius,Oak chips soaked in Islay whisky 50g,0,0,0,0,0,0,0,0,0,Oysters,Hickory smoked ham,Rocky Road,0
11,2,Trashy Blonde,You Know You Shouldn't,2008-04-01,"A titillating, neurotic, peroxide punk of a Pa...",https://images.punkapi.com/v2/2.png,4.1,41.5,1010,1041.7,15.0,15.0,4.4,76.0,20,litres,25,litres,Be careful not to collect too much wort from t...,Sam Mason <samjbmason>,69,celsius,0,18,celsius,0,0,0,0,0,0,0,0,0,0,Fresh crab with lemon,Garlic butter dipping sauce,Goats cheese salad,Creamy lemon bar doused in powdered sugar
17,25,Bad Pixie,Spiced Wheat Beer.,2008-10-01,"2008 Prototype beer, a 4.7% wheat ale with cru...",https://images.punkapi.com/v2/25.png,4.7,45.0,1010,1047.0,8.0,4.0,4.4,79.0,20,litres,25,litres,Make sure you have plenty of room in the ferme...,Sam Mason <samjbmason>,67,celsius,75,19,celsius,"Crushed juniper berries: 12.5g, Lemon peel: 18.8g",0,0,0,0,0,0,0,0,0,Poached sole fillet with capers,Summer fruit salad,Banana split,0
14,22,Devine Rebel (w/ Mikkeller),Oak-aged Barley Wine.,2008-12-01,"Two of Europe's most experimental, boundary-pu...",https://images.punkapi.com/v2/22.png,12.5,100.0,1030,1093.0,36.0,18.0,4.4,68.0,20,litres,25,litres,Rack off to a secondary fermenter before pitch...,Sam Mason <samjbmason>,65,celsius,90,19,celsius,"Part-aged in oak barrels, finished with champa...",0,0,0,0,0,0,0,0,0,Stilton on gingerbread biscuits,Pot roasted artichokes,Lamb chops with caramelised figs,0

#### 3.How many beers are there in the dataset?

In [64]:
df['Name'].count()

25

#### 4.What is tagline of the beer named "Buzz"?

In [72]:
x=df[["Name","tagline"]]
x.head()

             Name                        tagline
0            Buzz      A Real Bitter Experience.
1      Bramling X  Single Hop IPA Series - 2011.
2  Misspent Youth       Milk & Honey Scotch Ale.
3   Arcade Nation            Seasonal Black IPA.
4        Movember         Moustache-Worthy Beer.

In [108]:
#y=x[x["Name"]=="Buzz"]
x.loc[0]['tagline']

'A Real Bitter Experience.'

#### 5.What is tagline of beer named "Movember"?

In [107]:
z=x.loc[4]['tagline']
z

'Moustache-Worthy Beer.'

#### 6.How many beers have ibu levels above average?

In [120]:
#limit=50.58
#column_name=ibu
count=(df["ibu"] > limit).sum()
count

10